# Generated by Django 4.2.1 on 2023-05-05 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_created_date_alter_car_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank='true', default=datetime.datetime(2023, 5, 5, 17, 16, 58, 895028)),
        ),
    ]
