# Generated by Django 4.2.1 on 2023-05-08 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_created_date_alter_car_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank='true', default=datetime.datetime(2023, 5, 8, 16, 58, 42, 360816)),
        ),
    ]
