# Generated by Django 4.2.1 on 2023-05-08 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_alter_car_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank='true', default=datetime.datetime(2023, 5, 8, 19, 18, 55, 850327)),
        ),
    ]
